Welcomepage
brandonwu32/seacologywebsite pull request #5
Opened 2024-11-06 03:39 UTC by KatiaJacoby

Reimbursement: Created popups using react and use-state
Project Proposal Form and Agreement Form: logging functionality

2024-11-08 21:26 UTC, brandonwu32 reviewed
Great job guys! There were a lot of parts to this task but I think you guys understand exactly what the vision is for this part. We should try to be more consistent with our styling across each page so make sure communication is good between you two regarding CSS. The Figma should be the thing both of you try to follow.

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/grantagreementform/page.js
you can remove first and last name fields

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/grantagreementform/page.js
the bubble to submit the file: the top edge should line up with the top side of the form box on the left side

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/projectproporsalform/page.js
The folder is projectproposal (spelling error)

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/projectproporsalform/page.js
Remove personal information fields, they are picked up when we log in

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/projectproporsalform/page.js
I think the fields are a different style than the forms on the other pages. Let's try to keep the styles consistent. For example, conservation agreements has border color light blue, and the field height is larger. The blue button on this page is a different shade of blue than the blue button on conservation agreements. Overall, try to make consistent styling choices.

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/reimbursment/page.js
Spelling error: Reimbursement (missing an e on the folder and filenames)

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/reimbursment/page.js
This style is a little more consistent with conservationagreement but still not exact. The field width is smaller than in conservationagreement. There is no big blue border around everything. There are 2 lines in the header here but 1 everywhere else. Remove personal information fields. Button shade..., The drop down for the selection fields shouldn't be there permanently. They should follow the drop down we made for the navbar where they disappear after hover off

2024-11-08 21:26 UTC, brandonwu32 commented on src/app/welcome/page.js
The buttons should have position absolute, they should not move around when scrolling. The image is pretty grainy, try using an SVG rather than a PNG.

2024-11-10 21:12 UTC, tbhakhri requested changes
Great job you guys! A couple of CSS comments, you guys have some duplicate pages/pages with the same name which is a bitttt tough to follow. Make those changes and remove redunancies!

2024-11-12 01:09 UTC, tbhakhri requested changes
One last instance of percentage!

2024-11-12 01:09 UTC, tbhakhri commented on src/app/welcome/page.css
>      padding: 5px 0;
percentages!

2024-11-15 01:56 UTC, brandonwu32 reviewed
As talked about during the standup, we no longer need multiple bubbles in each form, since the file upload input tag can take in different kinds of files we just need 1 bubble. Maybe we don't even need to use the bubble, we can just have a field to input files like when you apply to internships

2024-11-19 04:52 UTC, tbhakhri approved these changes
good to merge

2024-11-19 05:14 UTC, KatiaJacoby commented
Slayed so hard
Made popups and moved bubbles around

2024-11-19 05:14 UTC, merged